# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42339a3bfe060f7cb0f913d9233de88106d8490c4bb1299968e43d42b8b738c665ae9e83f28de93ea9ba91c0c8f87a0843af197a58bef49e70ea92f308f7df70

test:
  secret_key_base: aea5092cba00c3f2f80d07eefe5b4d6bbb696769d23b877c084cc24b6725e926633a9f7780808eeb1b6b723ea67b48ce264515e1bc1d538f95e6ff25205aa938

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
